baseURL = "https://zo0o0ot.github.io/future-imperfect-test/"
languageCode = "en-us"
title = "My New Hugo Site"
publishDir = "docs"
theme = "hugo_theme_robust"
[params.author]
  thumbnail = "images/avatar.jpg"
  name = "John Doe"
  description = "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit</p><p>sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>"
  facebook = "https://www.facebook.com/daisuke.tsuji.735"
  twitter = "https://twitter.com/dim0627"
  github = "https://github.com/dim0627"

[outputs]
page = [ "HTML", "AMP" ] # if you want AMP enable.
