---
pages:
- posts/my-foresty-addition.md
- posts/forestry-number-two.md
- posts/another-post.md
- posts/hopeful-post.md
hide_body: false
fields:
- name: date
  label: Date
  type: field_group
  hidden: false
  default: {}
