---
pages:
- posts/date-test.md
- posts/post-post-post.md
- posts/more-posting-hope.md
- posts/my-foresty-addition.md
- posts/forestry-number-two.md
- posts/another-post.md
- posts/hopeful-post.md
hide_body: false
fields:
- type: datetime
  label: Date
  name: date
  default: 2017-09-15 00:00:00 -0500
